package com.seller.dao;

import com.github.pagehelper.Page;
import com.seller.dao.model.OrderMaster;
import com.seller.dao.model.OrderMasterExample;
import java.util.List;

import com.seller.util.pagehelper.Pagination;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    long countByExample(OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    int deleteByExample(OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    int insert(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    int insertSelective(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    List<OrderMaster> selectByExampleWithRowbounds(OrderMasterExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    List<OrderMaster> selectByExample(OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    OrderMaster selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderMaster record, @Param("example") OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    int updateByExample(@Param("record") OrderMaster record, @Param("example") OrderMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    int updateByPrimaryKeySelective(OrderMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    int updateByPrimaryKey(OrderMaster record);

    Page<OrderMaster> getPage(Pagination condition);
}