package com.seller.dao;

import com.seller.dao.model.SellerInfo;
import com.seller.dao.model.SellerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SellerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    long countByExample(SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    int deleteByExample(SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    int deleteByPrimaryKey(String sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    int insert(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    int insertSelective(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    List<SellerInfo> selectByExampleWithRowbounds(SellerInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    List<SellerInfo> selectByExample(SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    SellerInfo selectByPrimaryKey(String sellerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") SellerInfo record, @Param("example") SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    int updateByExample(@Param("record") SellerInfo record, @Param("example") SellerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    int updateByPrimaryKeySelective(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    int updateByPrimaryKey(SellerInfo record);
}