package com.seller.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrderMaster implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String buyerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_phone
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String buyerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_address
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String buyerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyer_openid
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String buyerOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_amount
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.order_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Byte orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.pay_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_id
     *
     * @return the value of order_master.order_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_id
     *
     * @param orderId the value for order_master.order_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_name
     *
     * @return the value of order_master.buyer_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_name
     *
     * @param buyerName the value for order_master.buyer_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_phone
     *
     * @return the value of order_master.buyer_phone
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getBuyerPhone() {
        return buyerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_phone
     *
     * @param buyerPhone the value for order_master.buyer_phone
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setBuyerPhone(String buyerPhone) {
        this.buyerPhone = buyerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_address
     *
     * @return the value of order_master.buyer_address
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getBuyerAddress() {
        return buyerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_address
     *
     * @param buyerAddress the value for order_master.buyer_address
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setBuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyer_openid
     *
     * @return the value of order_master.buyer_openid
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getBuyerOpenid() {
        return buyerOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyer_openid
     *
     * @param buyerOpenid the value for order_master.buyer_openid
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setBuyerOpenid(String buyerOpenid) {
        this.buyerOpenid = buyerOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_amount
     *
     * @return the value of order_master.order_amount
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_amount
     *
     * @param orderAmount the value for order_master.order_amount
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_status
     *
     * @return the value of order_master.order_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_status
     *
     * @param orderStatus the value for order_master.order_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.pay_status
     *
     * @return the value of order_master.pay_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.pay_status
     *
     * @param payStatus the value for order_master.pay_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.create_time
     *
     * @return the value of order_master.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.create_time
     *
     * @param createTime the value for order_master.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.update_time
     *
     * @return the value of order_master.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.update_time
     *
     * @param updateTime the value for order_master.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_master
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", buyerName=").append(buyerName);
        sb.append(", buyerPhone=").append(buyerPhone);
        sb.append(", buyerAddress=").append(buyerAddress);
        sb.append(", buyerOpenid=").append(buyerOpenid);
        sb.append(", orderAmount=").append(orderAmount);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}