package com.seller.dao.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.seller.util.enums.EnumUtil;
import com.seller.util.enums.OrderStatusEnum;
import com.seller.util.enums.ProductStatusEnum;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductInfo implements Serializable {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_price
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_stock
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Integer productStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_description
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String productDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_icon
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String productIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Byte productStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.category_type
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Integer categoryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_info
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_price
     *
     * @return the value of product_info.product_price
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_price
     *
     * @param productPrice the value for product_info.product_price
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_stock
     *
     * @return the value of product_info.product_stock
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Integer getProductStock() {
        return productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_stock
     *
     * @param productStock the value for product_info.product_stock
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setProductStock(Integer productStock) {
        this.productStock = productStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_description
     *
     * @return the value of product_info.product_description
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_description
     *
     * @param productDescription the value for product_info.product_description
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_icon
     *
     * @return the value of product_info.product_icon
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getProductIcon() {
        return productIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_icon
     *
     * @param productIcon the value for product_info.product_icon
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setProductIcon(String productIcon) {
        this.productIcon = productIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_status
     *
     * @return the value of product_info.product_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Byte getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_status
     *
     * @param productStatus the value for product_info.product_status
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setProductStatus(Byte productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.category_type
     *
     * @return the value of product_info.category_type
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Integer getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.category_type
     *
     * @param categoryType the value for product_info.category_type
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setCategoryType(Integer categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.update_time
     *
     * @return the value of product_info.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.update_time
     *
     * @param updateTime the value for product_info.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */

    @JsonIgnore
    public ProductStatusEnum getProductStatusEnum() {
        return EnumUtil.getCode(productStatus,ProductStatusEnum.class);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", productStock=").append(productStock);
        sb.append(", productDescription=").append(productDescription);
        sb.append(", productIcon=").append(productIcon);
        sb.append(", productStatus=").append(productStatus);
        sb.append(", categoryType=").append(categoryType);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}