package com.seller.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ProductCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_type
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Integer categoryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_category
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_id
     *
     * @return the value of product_category.category_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_id
     *
     * @param categoryId the value for product_category.category_id
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_name
     *
     * @return the value of product_category.category_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_name
     *
     * @param categoryName the value for product_category.category_name
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_type
     *
     * @return the value of product_category.category_type
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Integer getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_type
     *
     * @param categoryType the value for product_category.category_type
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setCategoryType(Integer categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.create_time
     *
     * @return the value of product_category.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.create_time
     *
     * @param createTime the value for product_category.create_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.update_time
     *
     * @return the value of product_category.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.update_time
     *
     * @param updateTime the value for product_category.update_time
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Jul 14 22:04:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryId=").append(categoryId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", categoryType=").append(categoryType);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}