package com.seller.dao.model;

import java.io.Serializable;
import java.util.Date;

public class SellerInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.seller_id
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.username
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.password
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.openid
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.create_time
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.update_time
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.seller_id
     *
     * @return the value of seller_info.seller_id
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.seller_id
     *
     * @param sellerId the value for seller_info.seller_id
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.username
     *
     * @return the value of seller_info.username
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.username
     *
     * @param username the value for seller_info.username
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.password
     *
     * @return the value of seller_info.password
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.password
     *
     * @param password the value for seller_info.password
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.openid
     *
     * @return the value of seller_info.openid
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.openid
     *
     * @param openid the value for seller_info.openid
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.create_time
     *
     * @return the value of seller_info.create_time
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.create_time
     *
     * @param createTime the value for seller_info.create_time
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.update_time
     *
     * @return the value of seller_info.update_time
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.update_time
     *
     * @param updateTime the value for seller_info.update_time
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated Thu Aug 02 15:00:16 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sellerId=").append(sellerId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", openid=").append(openid);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}